export const GETINITDATA = 'GETINITDATA';
export const GETARTCILES = 'GETARTICLES';
export const ARTICLEBYCATEGORY = 'ARTICLEBYCATEGORY';
export const ISLOADING = 'ISLOADING';
export const GETONEARTICLE = 'GETONEARTICLE';
