export const GETINITDATA = 'GETINITDATA';
export const GETARTCILES = 'GETARTICLES';
export const ISLOADING = 'ISLOADING';
export const GETONEARTICLE = 'GETONEARTICLE';
export const ADDCRUMBS = 'ADDCRUMBS';
export const REMOVECRUMBS = 'REMOVECRUMBS';
